[package]
name = "zrsh"
version = "0.1.0"
authors = ["zongziren <zsr1341864378@mail.ustc.edu.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.1.1"